apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfacto
  labels:
    app.kubernetes.io/name: postfacto
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: postfacto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postfacto
        version: main
    spec:
      containers:
        - name: postfacto
          image: postfacto/postfacto:4.3.0
          imagePullPolicy: Always
          env:
          - name: POSTGRES_IP
            valueFrom:
              configMapKeyRef:
                name: "postgres"
                key: "ip"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "postfacto-postgresql"
                key: postgres-password
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "postfacto-redis"
                key: redis-password
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: "secret-key"
                key: "secret-key-base"
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "oauth"
                key: "client-id"
          - name: DATABASE_URL
            value: "postgres://postgres:$(POSTGRES_PASSWORD)@10.41.208.3"
          - name: REDIS_URL
            value: "redis://:$(REDIS_PASSWORD)@postfacto-redis-master"
          - name: DISABLE_SSL_REDIRECT
            value: "false"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: 0.5Gi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 9
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 40
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 3
